<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::disableForeignKeyConstraints();

        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->boolean('status');
            $table
                ->bigInteger('created_by_id')
                ->unsigned()
                ->nullable();
            $table
                ->bigInteger('updated_by_id')
                ->unsigned()
                ->nullable();
            $table->timestamps();
        });

        Schema::enableForeignKeyConstraints();

        DB::table('countries')->insert([
            ['id' => 1, 'name' => 'Brasil', 'status' => true],
            ['id' => 2, 'name' => 'Afeganistão', 'status' => true],
            ['id' => 3, 'name' => 'África do Sul', 'status' => true],
            ['id' => 4, 'name' => 'Albânia', 'status' => true],
            ['id' => 5, 'name' => 'Alemanha', 'status' => true],
            ['id' => 6, 'name' => 'Andorra', 'status' => true],
            ['id' => 7, 'name' => 'Angola', 'status' => true],
            ['id' => 8, 'name' => 'Antígua e Barbuda', 'status' => true],
            ['id' => 9, 'name' => 'Arábia Saudita', 'status' => true],
            ['id' => 10, 'name' => 'Argélia', 'status' => true],
            ['id' => 11, 'name' => 'Argentina', 'status' => true],
            ['id' => 12, 'name' => 'Armênia', 'status' => true],
            ['id' => 13, 'name' => 'Austrália', 'status' => true],
            ['id' => 14, 'name' => 'Áustria', 'status' => true],
            ['id' => 15, 'name' => 'Azerbaijão', 'status' => true],
            ['id' => 16, 'name' => 'Bahamas', 'status' => true],
            ['id' => 17, 'name' => 'Bahrein', 'status' => true],
            ['id' => 18, 'name' => 'Bangladesh', 'status' => true],
            ['id' => 19, 'name' => 'Barbados', 'status' => true],
            ['id' => 20, 'name' => 'Bélgica', 'status' => true],
            ['id' => 21, 'name' => 'Belize', 'status' => true],
            ['id' => 22, 'name' => 'Benim', 'status' => true],
            ['id' => 23, 'name' => 'Bielorrússia', 'status' => true],
            ['id' => 24, 'name' => 'Bolívia', 'status' => true],
            ['id' => 25, 'name' => 'Bósnia e Herzegovina', 'status' => true],
            ['id' => 26, 'name' => 'Botswana', 'status' => true],
            ['id' => 27, 'name' => 'Brunei', 'status' => true],
            ['id' => 28, 'name' => 'Bulgária', 'status' => true],
            ['id' => 29, 'name' => 'Burquina Fasso', 'status' => true],
            ['id' => 30, 'name' => 'Burundi', 'status' => true],
            ['id' => 31, 'name' => 'Butão', 'status' => true],
            ['id' => 32, 'name' => 'Cabo Verde', 'status' => true],
            ['id' => 33, 'name' => 'Camarões', 'status' => true],
            ['id' => 34, 'name' => 'Camboja', 'status' => true],
            ['id' => 35, 'name' => 'Canadá', 'status' => true],
            ['id' => 36, 'name' => 'Catar', 'status' => true],
            ['id' => 37, 'name' => 'Cazaquistão', 'status' => true],
            ['id' => 38, 'name' => 'Chade', 'status' => true],
            ['id' => 39, 'name' => 'Chile', 'status' => true],
            ['id' => 40, 'name' => 'China', 'status' => true],
            ['id' => 41, 'name' => 'Chipre', 'status' => true],
            ['id' => 42, 'name' => 'Colômbia', 'status' => true],
            ['id' => 43, 'name' => 'Comores', 'status' => true],
            ['id' => 44, 'name' => 'República Democrática do Congo', 'status' => true],
            ['id' => 45, 'name' => 'República do Congo', 'status' => true],
            ['id' => 46, 'name' => 'Coreia do Norte', 'status' => true],
            ['id' => 47, 'name' => 'Coreia do Sul', 'status' => true],
            ['id' => 48, 'name' => 'Costa do Marfim', 'status' => true],
            ['id' => 49, 'name' => 'Costa Rica', 'status' => true],
            ['id' => 50, 'name' => 'Croácia', 'status' => true],
            ['id' => 51, 'name' => 'Cuba', 'status' => true],
            ['id' => 52, 'name' => 'Dinamarca', 'status' => true],
            ['id' => 53, 'name' => 'Djibouti', 'status' => true],
            ['id' => 54, 'name' => 'Dominica', 'status' => true],
            ['id' => 55, 'name' => 'Egito', 'status' => true],
            ['id' => 56, 'name' => 'Emirados Árabes Unidos', 'status' => true],
            ['id' => 57, 'name' => 'El Salvador', 'status' => true],
            ['id' => 58, 'name' => 'Equador', 'status' => true],
            ['id' => 59, 'name' => 'Eritreia', 'status' => true],
            ['id' => 60, 'name' => 'Eslováquia', 'status' => true],
            ['id' => 61, 'name' => 'Eslovênia', 'status' => true],
            ['id' => 62, 'name' => 'Espanha', 'status' => true],
            ['id' => 63, 'name' => 'Essuatíni', 'status' => true],
            ['id' => 64, 'name' => 'Estados Unidos', 'status' => true],
            ['id' => 65, 'name' => 'Estônia', 'status' => true],
            ['id' => 66, 'name' => 'Etiópia', 'status' => true],
            ['id' => 67, 'name' => 'Fiji', 'status' => true],
            ['id' => 68, 'name' => 'Filipinas', 'status' => true],
            ['id' => 69, 'name' => 'Finlândia', 'status' => true],
            ['id' => 70, 'name' => 'França', 'status' => true],
            ['id' => 71, 'name' => 'Gabão', 'status' => true],
            ['id' => 72, 'name' => 'Gâmbia', 'status' => true],
            ['id' => 73, 'name' => 'Gana', 'status' => true],
            ['id' => 74, 'name' => 'Geórgia', 'status' => true],
            ['id' => 75, 'name' => 'Granada', 'status' => true],
            ['id' => 76, 'name' => 'Grécia', 'status' => true],
            ['id' => 77, 'name' => 'Guiana', 'status' => true],
            ['id' => 78, 'name' => 'Guatemala', 'status' => true],
            ['id' => 79, 'name' => 'Guiné', 'status' => true],
            ['id' => 80, 'name' => 'Guiné-Bissau', 'status' => true],
            ['id' => 81, 'name' => 'Guiné Equatorial', 'status' => true],
            ['id' => 82, 'name' => 'Haiti', 'status' => true],
            ['id' => 83, 'name' => 'Honduras', 'status' => true],
            ['id' => 84, 'name' => 'Hungria', 'status' => true],
            ['id' => 85, 'name' => 'Iêmen', 'status' => true],
            ['id' => 86, 'name' => 'Islândia', 'status' => true],
            ['id' => 87, 'name' => 'Índia', 'status' => true],
            ['id' => 88, 'name' => 'Indonésia', 'status' => true],
            ['id' => 89, 'name' => 'Irã', 'status' => true],
            ['id' => 90, 'name' => 'Iraque', 'status' => true],
            ['id' => 91, 'name' => 'Irlanda', 'status' => true],
            ['id' => 92, 'name' => 'Israel', 'status' => true],
            ['id' => 93, 'name' => 'Itália', 'status' => true],
            ['id' => 94, 'name' => 'Jamaica', 'status' => true],
            ['id' => 95, 'name' => 'Japão', 'status' => true],
            ['id' => 96, 'name' => 'Jordânia', 'status' => true],
            ['id' => 97, 'name' => 'Kiribati', 'status' => true],
            ['id' => 98, 'name' => 'Kosovo', 'status' => true],
            ['id' => 99, 'name' => 'Kuwait', 'status' => true],
            ['id' => 100, 'name' => 'Laos', 'status' => true],
            ['id' => 101, 'name' => 'Lesoto', 'status' => true],
            ['id' => 102, 'name' => 'Letônia', 'status' => true],
            ['id' => 103, 'name' => 'Líbano', 'status' => true],
            ['id' => 104, 'name' => 'Libéria', 'status' => true],
            ['id' => 105, 'name' => 'Líbia', 'status' => true],
            ['id' => 106, 'name' => 'Liechtenstein', 'status' => true],
            ['id' => 107, 'name' => 'Lituânia', 'status' => true],
            ['id' => 108, 'name' => 'Luxemburgo', 'status' => true],
            ['id' => 109, 'name' => 'Macedônia do Norte', 'status' => true],
            ['id' => 110, 'name' => 'Madagascar', 'status' => true],
            ['id' => 111, 'name' => 'Malawi', 'status' => true],
            ['id' => 112, 'name' => 'Malásia', 'status' => true],
            ['id' => 113, 'name' => 'Maldivas', 'status' => true],
            ['id' => 114, 'name' => 'Mali', 'status' => true],
            ['id' => 115, 'name' => 'Malta', 'status' => true],
            ['id' => 116, 'name' => 'Marrocos', 'status' => true],
            ['id' => 117, 'name' => 'Ilhas Marshall', 'status' => true],
            ['id' => 118, 'name' => 'Mauritânia', 'status' => true],
            ['id' => 119, 'name' => 'Ilhas Maurício', 'status' => true],
            ['id' => 120, 'name' => 'México', 'status' => true],
            ['id' => 121, 'name' => 'Mianmar', 'status' => true],
            ['id' => 122, 'name' => 'Micronésia', 'status' => true],
            ['id' => 123, 'name' => 'Moldávia', 'status' => true],
            ['id' => 124, 'name' => 'Mônaco', 'status' => true],
            ['id' => 125, 'name' => 'Mongólia', 'status' => true],
            ['id' => 126, 'name' => 'Montenegro', 'status' => true],
            ['id' => 127, 'name' => 'Moçambique', 'status' => true],
            ['id' => 128, 'name' => 'Namíbia', 'status' => true],
            ['id' => 129, 'name' => 'Nauru', 'status' => true],
            ['id' => 130, 'name' => 'Nepal', 'status' => true],
            ['id' => 131, 'name' => 'Nicarágua', 'status' => true],
            ['id' => 132, 'name' => 'Níger', 'status' => true],
            ['id' => 133, 'name' => 'Nigéria', 'status' => true],
            ['id' => 134, 'name' => 'Noruega', 'status' => true],
            ['id' => 135, 'name' => 'Nova Zelândia', 'status' => true],
            ['id' => 136, 'name' => 'Omã', 'status' => true],
            ['id' => 137, 'name' => 'Países Baixos', 'status' => true],
            ['id' => 138, 'name' => 'Paquistão', 'status' => true],
            ['id' => 139, 'name' => 'Palau', 'status' => true],
            ['id' => 140, 'name' => 'Palestina', 'status' => true],
            ['id' => 141, 'name' => 'Panamá', 'status' => true],
            ['id' => 142, 'name' => 'Papua-Nova Guiné', 'status' => true],
            ['id' => 143, 'name' => 'Paraguai', 'status' => true],
            ['id' => 144, 'name' => 'Peru', 'status' => true],
            ['id' => 145, 'name' => 'Polônia', 'status' => true],
            ['id' => 146, 'name' => 'Portugal', 'status' => true],
            ['id' => 147, 'name' => 'Quênia', 'status' => true],
            ['id' => 148, 'name' => 'Quirguistão', 'status' => true],
            ['id' => 149, 'name' => 'Reino Unido', 'status' => true],
            ['id' => 150, 'name' => 'República Centro-Africana', 'status' => true],
            ['id' => 151, 'name' => 'República Tcheca', 'status' => true],
            ['id' => 152, 'name' => 'República Dominicana', 'status' => true],
            ['id' => 153, 'name' => 'Romênia', 'status' => true],
            ['id' => 154, 'name' => 'Ruanda', 'status' => true],
            ['id' => 155, 'name' => 'Rússia', 'status' => true],
            ['id' => 156, 'name' => 'Ilhas Salomão', 'status' => true],
            ['id' => 157, 'name' => 'San Marino', 'status' => true],
            ['id' => 158, 'name' => 'São Cristóvão e Neves', 'status' => true],
            ['id' => 159, 'name' => 'Santa Lúcia', 'status' => true],
            ['id' => 160, 'name' => 'São Tomé e Príncipe', 'status' => true],
            ['id' => 161, 'name' => 'São Vicente e Granadinas', 'status' => true],
            ['id' => 162, 'name' => 'Samoa', 'status' => true],
            ['id' => 163, 'name' => 'Senegal', 'status' => true],
            ['id' => 164, 'name' => 'Sérvia', 'status' => true],
            ['id' => 165, 'name' => 'Serra Leoa', 'status' => true],
            ['id' => 166, 'name' => 'Seicheles', 'status' => true],
            ['id' => 167, 'name' => 'Singapura', 'status' => true],
            ['id' => 168, 'name' => 'Síria', 'status' => true],
            ['id' => 169, 'name' => 'Somália', 'status' => true],
            ['id' => 170, 'name' => 'Sri Lanka', 'status' => true],
            ['id' => 171, 'name' => 'Sudão', 'status' => true],
            ['id' => 172, 'name' => 'Sudão do Sul', 'status' => true],
            ['id' => 173, 'name' => 'Suécia', 'status' => true],
            ['id' => 174, 'name' => 'Suíça', 'status' => true],
            ['id' => 175, 'name' => 'Suriname', 'status' => true],
            ['id' => 176, 'name' => 'Tajiquistão', 'status' => true],
            ['id' => 177, 'name' => 'Tailândia', 'status' => true],
            ['id' => 178, 'name' => 'Tanzânia', 'status' => true],
            ['id' => 179, 'name' => 'Timor-Leste', 'status' => true],
            ['id' => 180, 'name' => 'Togo', 'status' => true],
            ['id' => 181, 'name' => 'Tonga', 'status' => true],
            ['id' => 182, 'name' => 'Trindade e Tobago', 'status' => true],
            ['id' => 183, 'name' => 'Tunísia', 'status' => true],
            ['id' => 184, 'name' => 'Turquemenistão', 'status' => true],
            ['id' => 185, 'name' => 'Turquia', 'status' => true],
            ['id' => 186, 'name' => 'Tuvalu', 'status' => true],
            ['id' => 187, 'name' => 'Ucrânia', 'status' => true],
            ['id' => 188, 'name' => 'Uganda', 'status' => true],
            ['id' => 189, 'name' => 'Uruguai', 'status' => true],
            ['id' => 190, 'name' => 'Uzbequistão', 'status' => true],
            ['id' => 191, 'name' => 'Vanuatu', 'status' => true],
            ['id' => 192, 'name' => 'Venezuela', 'status' => true],
            ['id' => 193, 'name' => 'Vietnã', 'status' => true],
            ['id' => 194, 'name' => 'Zâmbia', 'status' => true],
            ['id' => 195, 'name' => 'Zimbábue', 'status' => true],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('countries');
    }
};
